spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/vs_rgr_db"
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
  liquibase:
    enabled: true
    change-log: "classpath:db/changelog/db.changelog-master.yaml"
